# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Desktop/New

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Desktop/New

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Desktop/New/CMakeFiles /home/pi/Desktop/New/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Desktop/New/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

# target to build an object file
cvclass.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cvclass.o
.PHONY : cvclass.o

# target to preprocess a source file
cvclass.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cvclass.i
.PHONY : cvclass.i

# target to generate assembly for a file
cvclass.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cvclass.s
.PHONY : cvclass.s

# target to build an object file
cvrltclass.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cvrltclass.o
.PHONY : cvrltclass.o

# target to preprocess a source file
cvrltclass.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cvrltclass.i
.PHONY : cvrltclass.i

# target to generate assembly for a file
cvrltclass.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cvrltclass.s
.PHONY : cvrltclass.s

# target to build an object file
mygeoclass.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/mygeoclass.o
.PHONY : mygeoclass.o

# target to preprocess a source file
mygeoclass.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/mygeoclass.i
.PHONY : mygeoclass.i

# target to generate assembly for a file
mygeoclass.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/mygeoclass.s
.PHONY : mygeoclass.s

# target to build an object file
mysquaresvecclass.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/mysquaresvecclass.o
.PHONY : mysquaresvecclass.o

# target to preprocess a source file
mysquaresvecclass.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/mysquaresvecclass.i
.PHONY : mysquaresvecclass.i

# target to generate assembly for a file
mysquaresvecclass.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/mysquaresvecclass.s
.PHONY : mysquaresvecclass.s

# target to build an object file
spclass.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/spclass.o
.PHONY : spclass.o

# target to preprocess a source file
spclass.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/spclass.i
.PHONY : spclass.i

# target to generate assembly for a file
spclass.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/spclass.s
.PHONY : spclass.s

# target to build an object file
test.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.o
.PHONY : test.o

# target to preprocess a source file
test.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.i
.PHONY : test.i

# target to generate assembly for a file
test.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.s
.PHONY : test.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... cvclass.o"
	@echo "... cvclass.i"
	@echo "... cvclass.s"
	@echo "... cvrltclass.o"
	@echo "... cvrltclass.i"
	@echo "... cvrltclass.s"
	@echo "... mygeoclass.o"
	@echo "... mygeoclass.i"
	@echo "... mygeoclass.s"
	@echo "... mysquaresvecclass.o"
	@echo "... mysquaresvecclass.i"
	@echo "... mysquaresvecclass.s"
	@echo "... spclass.o"
	@echo "... spclass.i"
	@echo "... spclass.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

